ci: windows builds will continue to build if failed to install depends via choco

diff --git a/.github/workflows/rust.yml b/.github/workflows/rust.yml
--- a/.github/workflows/rust.yml
+++ b/.github/workflows/rust.yml
@@ -93,7 +93,7 @@ jobs:
 
       - name: Install dependencies (Windows)
         if: runner.os == 'Windows'
-        run: choco install fd bat
+        run: choco install fd bat || echo "Ignored choco failure"
 
       - name: Build
         id: build_step
